CC=gcc

all : char int float double void

char :
	$(CC) char.c -o char

int :
	$(CC) int.c -o int

float :
	$(CC) float.c -o float

double :
	$(CC) double.c -o double

void :
	$(CC) void.c -o void

clean : 
	rm char	
	rm int 
	rm float 
	rm double 
	rm void

run_char :
	./char

run_int :
	./int

run_float :
	./float

run_double :
	./double

run_void :
	./void


