CC=gcc

macro :
	$(CC) macro_substitution.c -o macro_substitution

condition :
	$(CC) condition_compilation.c -o condition_compilation

inclusion :
	$(CC) inclusion_of_name_files.c -o inclusion

run_macro :
	./macro_substitution

run_cond :
	./condition_compilation

run_inclusion :
	./inclusion

clean :
	rm inclusion
	rm condition_compilation
	rm macro_substitution
